[project]
name = "homeassistant-getmymeter"
version = "0.1.2"
requires-python = ">=3.14.2"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]

[tool.ruff]
target-version = "py314"
line-length = 88

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN401",
  "COM812",
  "D203",
  "D213",
  "ISC001",
  "ARG001",
  "CPY001",
  "C901",
  "EM101",
  "EM102",
  "PLR0912",
  "PLR0915",
  "PLR2004",
  "TC001",
  "TC002",
  "TC003",
  "TRY003",
  "TRY301",
  "UP017",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
  "S101",
  "ANN001",
  "D102",
  "D105",
  "D107",
  "E501",
  "FLY002",
  "PT011",
  "PYI034",
  "SLF001",
]
